# Generated by Django 5.2.1 on 2025-05-27 13:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numtel', models.CharField(max_length=15)),
                ('adresse', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Central',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=200)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('central', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubs', to='airponFtth.central')),
            ],
        ),
        migrations.CreateModel(
            name='Chaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaines', to='airponFtth.hub')),
            ],
        ),
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_panne', models.CharField(choices=[('connexion', 'Perte de connexion'), ('debit', 'Débit faible'), ('fibre', 'Coupure fibre'), ('voip', 'Problème VoIP'), ('deco', 'Déconnexions fréquentes'), ('fixe', 'Problème de ligne fixe'), ('routeur', 'Erreur routeur/modem'), ('sync', 'Perte de synchronisation'), ('ip', 'Adresse IP erronée'), ('reseau', 'Panne générale réseau')], max_length=50)),
                ('description', models.TextField()),
                ('etat', models.CharField(max_length=100)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('abonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pannes', to='airponFtth.abonne')),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('chaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='airponFtth.chaine')),
            ],
        ),
        migrations.AddField(
            model_name='abonne',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnes', to='airponFtth.sub'),
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
