# Generated by Django 5.2.1 on 2025-05-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airponFtth', '0002_device_panneresau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panneresau',
            name='device',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='PanneResau',
        ),
    ]
