# Generated by Django 5.2.1 on 2025-05-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airponFtth', '0003_remove_panneresau_device_delete_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonne',
            name='email',
        ),
    ]
